### PR TITLE
Fix case of duplicate column names in deconstruct

### LINKED ISSUE #3: `Tables.columns(::Strapping.DeconstructedRowsIterator)` errors
I'm not sure if this is a bug, or I'm misunderstanding how Strapping works. The following gives an error and I'm not sure why:
```julia
using Strapping, StructTypes, Tables

const ids = Ref(0)
struct TestStruct
    a::Float64
    b::Float64
    id::Int
end

function TestStruct(a,b)
    global ids[] += 1
    TestStruct(a,b,ids[])
end

StructTypes.StructType(::Type{TestStruct}) = StructTypes.Struct()
StructTypes.idproperty(::Type{TestStruct}) = :id

data = [ TestStruct(rand(2)...) for n = 1:5]

tbl = Strapping.deconstruct(data)
```
Then gives
```julia
julia> Tables.columns(tbl)
ERROR: duplicate field name in NamedTuple: "a" is not unique
Stacktrace:
 [1] NamedTuple{(:a, :b, :id, :a, :b, :id, :a, :b, :id, :a, :b, :id, :a, :b, :id),T} where T<:Tuple(::Tuple{Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1}}) at ./boot.jl:549
 [2] macro expansion at /Users/eh540/.julia/packages/Tables/TjjiP/src/fallbacks.jl:0 [inlined]
 [3] allocatecolumns(::Tables.Schema{(:a, :b, :id, :a, :b, :id, :a, :b, :id, :a, :b, :id, :a, :b, :id),Tuple{Float64,Float64,Int64,Float64,Float64,Int64,Float64,Float64,Int64,Float64,Float64,Int64,Float64,Float64,Int64}}, ::Int64) at /Users/eh540/.julia/packages/Tables/TjjiP/src/fallbacks.jl:110
 [4] buildcolumns(::Tables.Schema{(:a, :b, :id, :a, :b, :id, :a, :b, :id, :a, :b, :id, :a, :b, :id),Tuple{Float64,Float64,Int64,Float64,Float64,Int64,Float64,Float64,Int64,Float64,Float64,Int64,Float64,Float64,Int64}}, ::Strapping.DeconstructedRowsIterator{TestStruct}) at /Users/eh540/.julia/packages/Tables/TjjiP/src/fallbacks.jl:125
 [5] columns(::Strapping.DeconstructedRowsIterator{TestStruct}) at /Users/eh540/.julia/packages/Tables/TjjiP/src/fallbacks.jl:228
 [6] top-level scope at REPL[32]:1
```
Calling `Tables.columntable(tbl)` runs into the same issue.

### PR DESCRIPTION
**Pull request by quinnj**
Fixes #3. The issue here was that after detecting the final column names
and types from the first element of a `Vector{T}`, we then passed those
names/types vectors to subsequent elements and they appended the same
names/types again. So we ended up with names * N and types * N, where N
is the number of elements in the original `Vector{T}`. The fix is pretty
easy: after we process the first element, save the names/types and use
those in the final DeconstructedRowIterator.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -121,3 +121,22 @@ ab6 = AB6(1, [3.14, 3.15, 3.16], AB(2, 0.01), [AB(10, 1.1), AB(11, 2.2), AB(12,
...
+struct TestStruct
+    a::Float64
+    b::Float64
+    id::Int
+end
+
+function TestStruct(a,b,id)
+    TestStruct(a,b,id)
+end
+
```
Comment (ericphanson) [inline test/runtests.jl]:
```suggestion
```
